package tn.esprit.javafx.service;

import tn.esprit.javafx.database.ReclamationDAO;
import tn.esprit.javafx.model.Reclamation;

import java.util.Date;
import java.util.List;

public class ReclamationService {
    
    private static final int STATIC_USER_ID = 1; // Static user ID as per requirements
    
    public List<Reclamation> getAllReclamations() {
        return ReclamationDAO.getAllReclamations();
    }
    
    public List<Reclamation> getReclamationsByUser() {
        // Using static user ID = 1 as per requirements
        return ReclamationDAO.getReclamationsByUserId(STATIC_USER_ID);
    }
    
    public Reclamation getReclamationById(int id) {
        return ReclamationDAO.getReclamationById(id);
    }
    
    public boolean addReclamation(String title, String email, String description) {
        // Using static user ID = 1 as per requirements
        Reclamation reclamation = new Reclamation(
            0, // ID will be generated by the database
            STATIC_USER_ID,
            title,
            email, // Email is stored in the Reclamation model but not in DB directly
            description,
            new Date(), // Current date
            "pending" // Default status
        );
        
        return ReclamationDAO.addReclamation(reclamation);
    }
    
    public boolean updateReclamation(int id, String title, String email, String description) {
        Reclamation reclamation = ReclamationDAO.getReclamationById(id);
        
        if (reclamation != null) {
            reclamation.setTitle(title);
            reclamation.setEmail(email);
            reclamation.setDescription(description);
            reclamation.setDate(new Date()); // Update date
            
            return ReclamationDAO.updateReclamation(reclamation);
        }
        
        return false;
    }
    
    public boolean deleteReclamation(int id) {
        return ReclamationDAO.deleteReclamation(id);
    }
    
    public boolean updateReclamationStatus(int id, String status) {
        return ReclamationDAO.updateReclamationStatus(id, status);
    }
    
    public List<Reclamation> getReclamationsByEmail(String email) {
        return ReclamationDAO.getReclamationsByEmail(email);
    }
}
