package tn.esprit.javafx.service;

import tn.esprit.javafx.database.ResponseDAO;
import tn.esprit.javafx.model.Response;

import java.util.Date;
import java.util.List;

public class ResponseService {
    
    public List<Response> getAllResponses() {
        return ResponseDAO.getAllResponses();
    }
    
    public List<Response> getResponsesByReclamationId(int reclamationId) {
        return ResponseDAO.getResponsesByReclamationId(reclamationId);
    }
    
    public Response getResponseById(int id) {
        return ResponseDAO.getResponseById(id);
    }
    
    public boolean addResponse(int reclamationId, String message) {
        Response response = new Response(
            0, // ID will be generated by the database
            reclamationId,
            message,
            new Date() // Current date
        );
        
        return ResponseDAO.addResponse(response);
    }
    
    public boolean updateResponse(int id, String message) {
        Response response = ResponseDAO.getResponseById(id);
        
        if (response != null) {
            response.setMessage(message);
            response.setDate(new Date()); // Update date
            
            return ResponseDAO.updateResponse(response);
        }
        
        return false;
    }
    
    public boolean deleteResponse(int id) {
        return ResponseDAO.deleteResponse(id);
    }
    
    public boolean hasResponses(int reclamationId) {
        List<Response> responses = getResponsesByReclamationId(reclamationId);
        return !responses.isEmpty();
    }
}
